# Generated by Django 4.2.1 on 2023-06-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0004_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
