# Generated by Django 4.2.1 on 2023-06-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaosNewsApp', '0006_alter_noticia_delete_alter_noticia_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
