# Generated by Django 4.2.1 on 2023-06-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0008_alter_noticia_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
