# Generated by Django 4.2.1 on 2023-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0015_rename_delete_noticia_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacada',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
    ]
