# Generated by Django 4.2.1 on 2023-07-11 03:24

import CaosNewsApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0016_noticia_destacada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenNoticia',
            fields=[
                ('id_imagen', models.AutoField(db_column='id_imagen', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=CaosNewsApp.models.get_image_upload_path)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='CaosNewsApp.noticia')),
            ],
        ),
    ]
