# Generated by Django 4.2.1 on 2023-07-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNewsApp', '0017_remove_noticia_imagen_imagennoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(db_column='id_pais', primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', null=True, on_delete=django.db.models.deletion.PROTECT, to='CaosNewsApp.pais'),
        ),
    ]
