# Generated by Django 4.2.3 on 2023-07-12 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaosNewsApp', '0018_pais_noticia_id_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleNoticia',
            fields=[
                ('id', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado')], max_length=1, null=True)),
                ('publicacion', models.DateTimeField(default=None, null=True)),
                ('revisada_y_publicada', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='CaosNewsApp.noticia')),
            ],
        ),
    ]
