# Generated by Django 4.2.3 on 2023-07-12 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CaosNewsApp', '0021_rename_revisada_y_publicada_detallenoticia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenoticia',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Aprobado'), ('R', 'Rechazado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detallenoticia',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallenoticia',
            name='publicacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
